const highlightWords = [
    // ["AD", "Automatic differentiation"],
    // ["AE", "Auto encoder"],
    // ["ARD", "Automatic Relevance Determination"],
    // ["ASR", "Automatic Speech Recognition"],
    // ["BNN", "Binary Neural Net"],
    // ["BPTS", "Backpropagation through structure"],
    // ["BPTT", "Back propagation through time"],
    // ["CNN", "Convolutional Neural network"],
    // ["COCO", "Common Objects in Context"],
    // ["CTC", "Connectionist Temporal Classification"],
      ["AD","Automatic differentiation"],
      ["AE","Auto encoder"],
      ["ARD","Automatic Relevance Determination"],           
      ["ASR","Automatic Speech Recognition"],
      ["BNN","Binary Neural Net"],
      ["BPTS","Backpropagation through structure"],
      ["BPTT","Back propagation through time"],
      ["CNN","Convolutional Neural network"],
      ["COCO","Common Objects in Context"],
      ["CTC","Connectionist Temporal Classification"],
      ["DBN","Deep Belief Network"],
      ["DCGAN","Deep Convolutional Generative Adversarial Networks"],
      ["DNN","Deep Neural Network"],
      ["EBM","Energy Based Model"],
      ["ELU","Exponential Linear Unit"],
      ["ESP","Enforced SubPopulations"],
      ["GA","Genetic algorithm"],
      ["GAN","Generative Adversarial Network"],
      ["GMM","Gaussian Mixture Model"],
      ["GRU","Gated Recurrent Unit"],
      ["HAM","Hierarchical Attentive Memory"],
      ["HMM","Hidden Markov Model"],
      ["HTM","Heirarchal temporal memory"],
      ["KNN","k-Nearest Neighbors"],
      ["LReLU","Leaky ReLU"],
      ["LSTM","Long short-term memory"],
      ["MCMC","Markov chain Monte Carlo"],
      ["MDP","Markov Decision Processes"],
      ["MLP","Multi-layer Perceptrons"],
      ["NE","NeuroEvolution"],
      ["NEAT","NeuroEvolution of Augmenting Topologies"],
      ["NLP","Natural Language Processing"],
      ["NMT","neural machine translation"],
      ["NTM","Neural Turing Machine"],
      ["OLS","Ordinary Least Squares Regression"],
      ["PAC-MDP","Probably Approximately Correct in Markov Decision Processes"],
      ["PCA","Principal component analysis"],
      ["PReLU","Paramaterized ReLU"],
      ["RBM","Restricted Boltzmann Machines"],
      ["ReLU","Rectified Linear Unit"],
      ["ResNet","Residual Neural Network"],
      ["RL","Reinforcement Learning"],
      ["RNN","Recurrent Neural Network"],
      ["RNTN","Recursive Neural Tensor Network"],
      ["RProp","resilient backpropagation"],
      ["RTRL","Real Time Recurrent Learning"],
      ["RVM","Relevance Vector Machine"],
      ["SANE","Symbiotic Adaptive NeuroEvolution"],
      ["SGD","Stochastic Gradient Descent"],
      ["SIFT","Scale-Invariant Feature Transform"],
      ["SRN","Simple Recurrent Network"],
      ["SVD","singular value decomposition"],
      ["SVM","Support Vector Machine"],
      ["TF","TensorFlow"],
      ["TFIDF","Term Frequency Inverse Document Frequency"],
      ["VLAD","Vector of Locally Aggregated Descriptors"],
      ["WFST","Weighted Finite-State Transducers"],
      ["ADT","Automatic Drum Transcription"],
      ["AE","AutoEncoder"],
      ["AMT","Automatic Music Transcription"],
      ["ANN","Artificial Neural Network"],
      ["ARNN","Anticipation Recurrent Neural Network"],
      ["BILSTM","Bidirectional Long Short-Term Memory"],
      ["BPTT","Back-Propagation Through Time"],
      ["BRNN","Bidirectional Recurrent Neural Network"],
      ["CDBN","Convolutional Deep Belief Networks"],
      ["CEC","Constant Error Carousel"],
      ["CLNN","ConditionaL Neural Networks"],
      ["CNN","Convolutional Neural Network"],
      ["ConvNet","Convolutional Neural Network"],
      ["CRBM","Conditional Restricted Boltzmann Machine"],
      ["CRNN","Convolutional Recurrent Neural Network"],
      ["DAE","Denoising AutoEncoder or Deep AutoEncoder"],
      ["DBM","Deep Boltzmann Machine"],
      ["DBN","Deep Belief Network"],
      ["DeconvNet","DeConvolutional Neural Network"],
      ["DL","Deep Learning"],
      ["DNN","Deep Neural Network"],
      ["DSN","Deep Stacking Network"],
      ["DWT","Discrete Wavelet Transform"],
      ["ELM","Extreme Learning Machine"],
      ["FC","Fully Connected"],
      ["FCN","Fully Convolutional Network"],
      ["FC-CNN","Fully Convolutional Convolutional Neural Network"],
      ["FC-LSTM","Fully Connected Long Short-Term Memory"],
      ["GBRCN","Gradient-Boosting Random Convolutional Network"],
      ["GFNN","Gradient Frequency Neural Networks"],
      ["GLCM","Gray Level Co-occurrence Matrix"],
      ["HAN","Hierarchical Attention Network"],
      ["HHDS","HipHop Dataset"],
      ["LSTM","Long Short-Term Memory"],
      ["MCLNN","Masked ConditionaL Neural Networks"],
      ["MER","Music Emotion Recognition"],
      ["MGR","Music Genre Recognition"],
      ["MLM","Music Language Models"],
      ["MLP","Multi-Layer Perceptron"],
      ["MRS","Music Recommender System"],
      ["MSDAE","Modified Sparse Denoising Autoencoder"],
      ["MSE","Mean Squared Error"],
      ["MSR","Music Style Recognition"],
      ["NN","Neural Network"],
      ["NNMODFF","Neural Network based Multi-Onset Detection Function Fusion"],
      ["ODF","Onset Detection Function"],
      ["PNN","Probabilistic Neural Network"],
      ["PReLU","Parametric Rectified Linear Unit"],
      ["RANSAC","RANdom SAmple Consensus"],
      ["RBM","Restricted Boltzmann Machine"],
      ["ReLU","Rectified Linear Unit"],
      ["RICNN","Rotation Invariant Convolutional Neural Network"],
      ["RNN","Recurrent Neural Network"],
      ["RTRL","Real-Time Recurrent Learning"],
      ["SAE","Stacked AE"],
      ["SDAE","Stacked DAE"],
      ["SGD","Stochastic Gradient Descent "],
      ["SVM","Support Vector Machine"],
      ["SVD","Singing Voice Detection"],
      ["SVS","Singing Voice Separation"],
      ["VAD","Voice Activity Detection"],
      ["VAE","Variational AutoEncoder"],
      ["VPNN","Vector Product Neural Network"],
      ["WPE","Weighted Prediction Error"],
      ["ACC","ACCuracy"],
      ["ACE","Alternating conditional expectation (ACE) algorithm"],
      ["ADA","AdaBoosted Decision Trees"],
      ["AdaBoost","Adaptive Boosting"],
      ["AdR","AdaBoostRegressor"],
      ["ADT","Automatic Drum Transcription"],
      ["AE","AutoEncoder"],
      ["AGI","Artificial General Intelligence"],
      ["AI","Artificial Intelligence"],
      ["AIWPSO","Adaptive Inertia Weight Particle Swarm Optimization"],
      ["AM","Activation Maximization"],
      ["AMT","Automatic Music Transcription"],
      ["ANN","Artificial Neural Network"],
      ["AR","Augmented Reality"],
      ["ARNN","Anticipation Recurrent Neural Network"],
      ["AUC","Area Under the (ROC) Curve"],
      ["BDT","Boosted Decision Tree"],
      ["BERT","Bidirectional Encoder Representation from Transformers"],
      ["BiFPN","Bidirectional Feature Pyramid Network"],
      ["BILSTM","Bidirectional Long Short-Term Memory"],
      ["BLEU","Bilingual Evaluation Understudy"],
      ["BN","Bayesian Network"],
      ["BNN","Bayesian Neural Network"],
      ["BP","BackPropagation"],
      ["BPMF","Bayesian Probabilistic Matrix Factorization"],
      ["BPTT","Backpropagation Through Time"],
      ["BQML","Big Query Machine Learning"],
      ["BRNN","Bidirectional Recurrent Neural Network"],
      ["BRR","Bayesian Ridge Regression"],
      ["CAE","Contractive AutoEncoder"],
      ["CALA","Continuous Action-set Learning Automata"],
      ["CART","Classification And Regression Tree"],
      ["CAV","Concept Activation Vectors"],
      ["CBI","Counterfactual Bias Insertion"],
      ["CBOW","Continuous Bag of Words"],
      ["CDBN","Convolutional Deep Belief Networks"],
      ["CE","Cross-Entropy"],
      ["CEC","Constant Error Carousel"],
      ["CF","Common Features"],
      ["CLNN","ConditionaL Neural Networks"],
      ["CMAC","Cerebellar Model Articulation Controller"],
      ["CMMs","Conditional Markov Model"],
      ["CNN","Convolutional Neural Network"],
      ["ConvNet","Convolutional Neural Network"],
      ["CRBM","Conditional Restricted Boltzmann Machine"],
      ["CRFs","Conditional Random Fields"],
      ["CRNN","Convolutional Recurrent Neural Network"],
      ["CTC","Connectionist Temporal Classification"],
      ["CTR","Collaborative Topic Regression"],
      ["CV","Coefficient of Variation"],
      ["CV","Computer Vision"],
      ["CSLR","Continuous Sign Language Recognition"],
      ["DAAF","Data Augmentation and Auxiliary Feature"],
      ["DAE","Denoising AutoEncoder or Deep AutoEncoder"],
      ["DBM","Deep Boltzmann Machine"],
      ["DBN","Deep Belief Network"],
      ["DBSCAN","Density-Based Spatial Clustering of Applications with Noise"],
      ["DCGAN","Deep Convolutional Generative Adversarial Network"],
      ["DCMDN","Deep Convolutional Mixture Density Network"],
      ["DE","Differential Evolution"],
      ["DeconvNet","DeConvolutional Neural Network"],
      ["DeepLIFT","Deep Learning Important FeaTures"],
      ["DL","Deep Learning"],
      ["DNN","Deep Neural Network"],
      ["DQN","Deep Q-Network"],
      ["DR","Detection Rate"],
      ["DSN","Deep Stacking Network"],
      ["DT","Decision Tree"],
      ["DTD","Deep Taylor Decomposition"],
      ["DWT","Discrete Wavelet Transform"],
      ["ELECTRA","Efficiently Learning an Encoder that Classifies Token Replacements Accurately"],
      ["ELM","Extreme Learning Machine"],
      ["ELMo","Embeddings from Language Models"],
      ["ELU","Exponential Linear Unit"],
      ["EM","Expectation maximization"],
      ["EMD","Entropy Minimization Discretization"],
      ["ERNIE","Enhanced Representation through kNowledge IntEgration"],
      ["ETL Pipeline","Extract Transform Load Pipeline"],
      ["EXT","Extremely Randomized Trees"],
      ["F Score","Harmonic Precision-Recall Mean"],
      ["FALA","Finite Action-set Learning Automata"],
      ["FC","Fully-Connected"],
      ["FC-CNN","Fully Convolutional Convolutional Neural Network"],
      ["FC-LSTM","Fully Connected Long Short-Term Memory"],
      ["FCM","Fuzzy C-Means"],
      ["FCN","Fully Convolutional Network"],
      ["FFT","Fast Fourier transform"],
      ["FLOP","Floating Point Operations"],
      ["FLOPS","Floating Point Operations Per Second"],
      ["FNN","Feedforward Neural Network"],
      ["FNR","False Negative Rate"],
      ["FPN","Feature Pyramid Network"],
      ["FPR","False Positive Rate"],
      ["FST","Finite state transducer"],
      ["FWIoU","Frequency Weighted Intersection over Union"],
      ["GA","Genetic Algorithm"],
      ["GALE","Global Aggregations of Local Explanations"],
      ["GAM","Generalized Additive Model"],
      ["GAM","Global Attribution Mapping"],
      ["GAN","Generative Adversarial Network"],
      ["GAP","Global Average Pooling"],
      ["GBRCN","Gradient-Boosting Random Convolutional Network"],
      ["GD","Gradient Descent"],
      ["GEBI","Global Explanation for Bias Identification"],
      ["GFNN","Gradient Frequency Neural Networks"],
      ["GLCM","Gray Level Co-occurrence Matrix"],
      ["Gloss2Text","A task of transforming raw glosses into meaningful sentences."],
      ["GloVE","Global Vectors"],
      ["GMM","Gaussian mixture model"],
      ["GPR","Gaussian Process Regression"],
      ["GPT","Generative Pre-trained Transformer"],
      ["GradCAM","GRADient-weighted Class Activation Mapping"],
      ["HamNoSys","Hamburg Sign Language Notation System"],
      ["HAN","Hierarchical Attention Network"],
      ["HCA","Hierarchical Clustering Analysis"],
      ["HDP","Hierarchical Dirichlet process"],
      ["HHDS","HipHop Dataset"],
      ["hLDA","Hierarchical Latent Dirichlet allocation"],
      ["HMM","Hidden Markov Model"],
      ["HNN","Hopfield Neural Network"],
      ["i.i.d","Independent and Identically Distributed"],
      ["ID3","Iterative Dichotomiser 3"],
      ["IDR","Input dependence rate"],
      ["IIR","Input independence rate"],
      ["INFD","Explanation Infidelity"],
      ["IoU","Jaccard index (intersection over union)"],
      ["ISIC","International Skin Imaging Collaboration"],
      ["k-NN","k-Nearest Neighbor"],
      ["KDE","Kernel Density Estimation"],
      ["KL","Kullback Leibler (KL) divergence"],
      ["kNN","k-Nearest Neighbours"],
      ["KRR","Kernel Ridge Regression"],
      ["LDA","Latent Dirichlet Allocation"],
      ["LDA","Linear Discriminant Analysis"],
      ["LDADE","Latent Dirichlet Allocation Differential Evolution"],
      ["LIME","Local Interpretable Model-agnostic Explanations"],
      ["LRP","Layer-wise Relevance Propagation"],
      ["LSA","Latent semantic analysis"],
      ["LSI","Latent Semantic Indexing"],
      ["LSTM","Long Short-Term Memory"],
      ["LTR","Learning To Rank"],
      ["LVQ","Learning Vector Quantization"],
      ["MADE","Masked Autoencoder for Distribution Estimation"],
      ["MAE","Mean Absolute Error"],
      ["MAF","Masked Autoregressive Flows"],
      ["MAP","Maximum A Posteriori (MAP) Estimation"],
      ["MAPE","Mean Absolute Prediction Error"],
      ["MART","Multiple Additive Regression Tree"],
      ["MaxEnt","Maximum Entropy"],
      ["MCLNN","Masked ConditionaL Neural Networks"],
      ["MCMC","Markov Chain Monte Carlo"],
      ["MCS","Model contrast score"],
      ["MDL","Minimum description length (MDL) principle"],
      ["MDN","Mixture Density Network"],
      ["MDP","Markov Decision Process"],
      ["MDRNN","Multidimensional recurrent neural network"],
      ["MER","Music Emotion Recognition"],
      ["MINT","Mutual Information based Transductive Feature Selection"],
      ["MIoU","Mean Intersection over Union"],
      ["ML","Machine Learning"],
      ["MLE","Maximum Likelihood Estimation"],
      ["MLM","Music Language Models"],
      ["MLP","Multi-Layer Perceptron"],
      ["MPA","Mean Pixel Accuracy"],
      ["MRR","Mean Reciprocal Rank"],
      ["MRS","Music Recommender System"],
      ["MSDAE","Modified Sparse Denoising Autoencoder"],
      ["MSE","Mean Squared Error"],
      ["MSR","Music Style Recognition"],
      ["NAS","Neural Architecture Search"],
      ["NB","Na ̈ıve Bayes"],
      ["NBKE","Na ̈ıve Bayes with Kernel Estimation"],
      ["NER","Named Entity Recognition"],
      ["NERQ","Named Entity Recognition in Query"],
      ["NF","Normalizing Flow"],
      ["NFL","No Free Lunch (NFL) theorem"],
      ["NLP","Natural Language Processing"],
      ["NLT","Neural Machine Translation"],
      ["NMS","Non Maximum Suppression"],
      ["NN","Neural Network"],
      ["NNMODFF","Neural Network based Multi-Onset Detection Function Fusion"],
      ["NPE","Neural Physical Engine"],
      ["NRMSE","Normalized RMSE"],
      ["NST","Neural Style Transfer"],
      ["NTM","Neural Turing Machine"],
      ["ODF","Onset Detection Function"],
      ["OLR","Ordinary Linear Regression"],
      ["OLS","Ordinary Least Squares"],
      ["PA","Pixel Accuracy"],
      ["PACO","Poisson Additive Co-Clustering"],
      ["PCA","Principal Component Analysis"],
      ["PEGASUS","Pre-training with Extracted Gap-Sentences for Abstractive Summarization"],
      ["PLSI","Probabilistic Latent Semantic Indexing"],
      ["PM","Project Manager"],
      ["PMF","Probabilistic Matrix Factorization"],
      ["PMI","Pointwise Mutual Information"],
      ["PNN","Probabilistic Neural Network"],
      ["POC","Proof of Concept"],
      ["POMDP","Partially Observable Markov Decision Process"],
      ["POS","Part of Speech (POS) Tagging"],
      ["PPMI","Positive Pointwise Mutual Information"],
      ["PReLU","Parametric Rectified Linear Unit-Yor Topic Modeling"],
      ["PU","Positive Unlabaled"],
      ["PYTM","Pitman"],
      ["RandNN","Random Neural Network"],
      ["RANSAC","RANdom SAmple Consensus"],
      ["RBF","Radial Basis Function"],
      ["RBFNN","Radial Basis Function Neural Network"],
      ["RBM","Restricted Boltzmann Machine"],
      ["ReLU","Rectified Linear Unit"],
      ["REPTree","Reduced Error Pruning Tree"],
      ["RF","Random Forest"],
      ["RGB","Red Green Blue color model"],
      ["RICNN","Rotation Invariant Convolutional Neural Network"],
      ["RIM","Recurrent Interence Machines"],
      ["RIPPER","Repeated Incremental Pruning to Produce Error Reduction"],
      ["RL","Reinforcement Learning"],
      ["RLFM","Regression based latent factors"],
      ["RMSE","Root MSE"],
      ["RNN","Recurrent Neural Network"],
      ["RNNLM","Recurrent Neural Network Language Model (RNNLM)"],
      ["RoBERTa","Robustly Optimized BERT Pretraining Approach"],
      ["ROC","Received Operating Characteristic"],
      ["ROI","Region Of Interest"],
      ["RR","Ridge Regression"],
      ["RTRL","Real-Time Recurrent Learning"],
      ["SAE","Stacked AE"],
      ["SARSA","State-Action-Reward-State-Action"],
      ["SBM","Stochastic block model"],
      ["SBO","Structured Bayesian optimization"],
      ["SBSE","Search-based software engineering"],
      ["SCH","Stochastic convex hull"],
      ["SDAE","Stacked DAE"],
      ["seq2seq","Sequence to Sequence Learning"],
      ["SER","Sentence Error Rate"],
      ["SGBoost","Stochastic Gradient Boosting"],
      ["SGD","Stochastic Gradient Descent"],
      ["SGVB","Stochastic Gradient Variational Bayes"],
      ["SHAP","SHapley Additive exPlanation"],
      ["SHLLE","Supervised Hessian Locally Linear Embedding"],
      ["Sign2(Gloss+Text)","Sign to Gloss and Text"],
      ["Sign2Gloss","A one to one translation from the single sign to the single gloss."],
      ["Sign2Text","A task of full translation from the sign language into the spoken one"],
      ["SLP","Single-Layer Perceptron"],
      ["SLRT","Sign Language Recognition Transformer"],
      ["SLT","Sign Language Translation"],
      ["SLTT","Sign Language Translation Transformer"],
      ["SMBO","Sequential Model-Based Optimization"],
      ["SOM","Self-Organizing Map"],
      ["SpRay","Spectral Relevance Analysis"],
      ["SSD","Single-Shot Detector"],
      ["SSL","Self-Supervised Learning"],
      ["SSVM","Smooth support vector machine"],
      ["ST","Style Transfer"],
      ["STDA","Style Transfer Data Augmentation"],
      ["STL","Selt-Taught Learning"],
      ["SVD","Singing Voice Detection"],
      ["SVD","Singular Value Decomposition"],
      ["SVM","Support Vector Machine"],
      ["SVR","Support Vector Regression"],
      ["SVS","Singing Voice Separation"],
      ["t-SNE","t-distributed stochastic neighbor embedding"],
      ["T5","Text-To-Text Transfer Transformer"],
      ["TD","Temporal Difference"],
      ["TDA","Targeted Data Augmentation"],
      ["TGAN","Temporal Generative Adversarial Network"],
      ["THAID","THeta Automatic Interaction Detection"],
      ["TINT","Tree-Interpreter"],
      ["TLFN","Time-Lagged Feedforward Neural Network"],
      ["TNR","True Negative Rate"],
      ["TPR","True Positive Rate"],
      ["TRPO","Trust Region Policy Optimization"],
      ["ULMFiT","Universal Language Model Fine-Tuning"],
      ["V-Net","Volumetric Convolutional neural network"],
      ["VAD","Voice Activity Detection"],
      ["VAE","Variational AutoEncoder"],
      ["VGG","Visual Geometry Group"],
      ["VPNN","Vector Product Neural Network"],
      ["VQ-VAE","Vector Quantized Variational Autoencoders"],
      ["VR","Virtual Reality"],
      ["WER","Word Error Rate"],
      ["WFST","Weighted finite-state transducer (WFST)"],
      ["WMA","Weighted Majority Algorithm"],
      ["WPE","Weighted Prediction Error"],
      ["XAI","Explainable Artificial Intelligence"],
      ["XGBoost","eXtreme Gradient Boosting"],
      ["YOLO","You Only Look Once"],
      ["A/D","Analog-to-Digital"],
      ["ABC","Atanasoff Berry Computer"],
      ["ACM","Association for Computing Machinery"],
      ["AI","Artificial Intelligence"],
      ["ALGOL","Algorithic Language"],
      ["ALU","Arithmetic Logic Unit"],
      ["AMD","Advanced Micro Devices"],
      ["APRANET","Advanced Research Project Agency Network"],
      ["ASCII","American Standard Code for Information Interchange"],
      ["BASIC","Beginners All-purpose Symbolic Instruction Code"],
      ["BCD","Binary Coded Decimal"],
      ["BIOS","Basic Inpute Output System"],
      ["BIPS","Billions of Instructions Per Second"],
      ["BPI","Bytes Per Inch"],
      ["CAD","Computer Aided Design"],
      ["CAE","Computer Aided Engineering"],
      ["CAN","Campus Area Network"],
      ["CASE","Computer Aided Software Engineering"],
      ["CD","Compact Disk"],
      ["CDC","Control Data Corporation"],
      ["CD-R","CD-Recordable"],
      ["CD-ROM","Compact Disk Read Only Memory"],
      ["CD-RW","CD Read/Write"],
      ["CL","Command Language"],
      ["CLI","Command Line Interface"],
      ["COBOL","Common Business Oriented"],
      ["CODASYL","Conference On Data Systems"],
      ["CPU","Central Processing Unit"],
      ["CRT","Cathode Ray Tube"],
      ["D/A","Digital-to-Analog"],
      ["DAT","Digital Audio Tape"],
      ["DBMS","Data Base Management System"],
      ["DBS","Demand Based Switching"],
      ["DDL","Data Definition Language"],
      ["DDS","Digital Data Storage"],
      ["DEC","Digital Equipment Corporation"],
      ["DMA","Direct Memory Access"],
      ["DNA","Digital Network Architecture"],
      ["DPI","Dots Per Inch"],
      ["DRAM","Dynamic RAM"],
      ["DSN","Distributed Systems Network"],
      ["DTS","Digital Theater System"],
      ["DVD","Digital Video/Versatile Disk"],
      ["EBCDIC","Extended Binary Coded Decimal Interchange Code"],
      ["EDSAC","Electronic Delay Storage Automatic Calculator"],
      ["EDVAC","Electronic Discrete Variable Automatic Calculator"],
      ["EFM","Eight-to-Fourteen Modulation"],
      ["ENIAC","Electronic Numerical Integrator And Calculator"],
      ["EPG","Electronic Programming Guide"],
      ["EPIC","Explicitly Parallel Instruction Computing"],
      ["EPROM","Erasable Programmable Read-Only Memory"],
      ["FAT","File Allocation Table"],
      ["FDM","Frequency Division Multiplexing"],
      ["FEP","Front End Processor"],
      ["FLOPS","Floating Point Operations Per Second"],
      ["FM","Frequency Modulation"],
      ["FMS","File Management System"],
      ["FORTRAN","FORmula TRANslation"],
      ["FSK","Frequency Shift Keying"],
      ["FTP","File Transfer Protocol"],
      ["GB","Giga Bytes"],
      ["GFLOPS","Giga FLOPS"],
      ["GHz","Giga Hertz"],
      ["GNU","Gnu Not Unix"],
      [">GPS","Global Positioning System"],
      ["GPRS","General Packet Radio Service"],
      ["GSM","Global System for Mobile communication"],
      ["GUI","Graphical User Interface"],
      ["HP","Hewlett Packard"],
      ["HSS","Hierarchical Storage System"],
      ["HTML","HyperText Markup Language"],
      ["HTTP","HyperText Transport Protocol"],
      ["IBM","International Business Machine"],
      ["IC","Integrated Circuit"],
      ["IDN","Integrated Digital Networks"],
      ["IP","Internet Protocol"],
      ["IrDA","Infrared Data Association"],
      ["ISDN","Integrated Services Digital Network"],
      ["ISP","Internet Service Provider"],
      ["JPEG","Joint Photographic Experts Group"],
      ["JRE","Java Runtime Engine"],
      ["JSP","Java Server Pages"],
      ["KB","Kilo Bytes"],
      ["KHz","Kilo Hertz"],
      ["LAN","Local Area Network"],
      ["LCD","Liquid Crystal Display"],
      ["LED","Light Emitting Diode"],
      ["LPM","Line Per Minute"],
      ["LSI","Large Scael Integration"],
      ["MAN","Metropolitan Area Network"],
      ["MAR","Memory Address Register"],
      ["MB","Mega Bytes"],
      ["MBR","Memory Buffer Register"],
      ["MHz","Mega Hertz"],
      ["MIDI","Musical Instrument Digital Interface"],
      ["MIPS","Millions of Instructions Per Second"],
      ["MNP","Microcom Network Protocol"],
      ["MPEG","Moving Pictures Experts Group"],
      ["MS-DOS","MicroSoft Disk Operating System"],
      ["MVT","Multiprogramming with Variable Tasks"],
      ["NIC","Network Interface Card"],
      ["NICNET","National Informatics Center NETwork"],
      ["NOS","Network Operating System"],
      ["OCR","Optical Character Recognition"],
      ["OMR","Optical Mark Reader"],
      ["ORACLE","Oak Ridge Automatic Computer and Logical Engine"],
      ["OS","Operating System"],
      ["OSI","Open System Interconnection"],
      ["OSS","Open Source Software"],
      ["PAN","Personal Area Network"],
      ["PC","Personal Computer"],
      ["PDF","Portable Document Format"],
      ["PDL","Program Design Language"],
      ["PDP","Program Data Processor"],
      ["PIP","Peripheral Interchange Program"],
      ["PNG","Portable Network Graphics"],
      ["PROM","Programmable Read-Only Memory"],
      [">PSD","Photoshop Document"],
      ["QoS","Quality of Service"],
      ["RAM","Random Access Memory"],
      ["ROM","Read Only Memory"],
      ["SDLC","Software Development Life Cycle"],
      ["SEQUEL","Structured English QUEry Language"],
      ["SGML","Syntax for Generalized Markup Language"],
      ["SIMM","Single In-line Memory Module"],
      ["SNA","Systems Network Architecture"],
      ["SNOBOL","StriNg Oriented and symBOlic Language"],
      ["SQL","Structured Query Language"],
      ["SRAM","Static RAM"],
      ["SSI","Small Scale Integration"],
      ["TB","Tera Bytes"],
      ["TCP","Transport Control Protocol"],
      ["TDM","Time Division Multiplexing"],
      ["UDP","User Datagram Protocol"],
      ["ULSI","Ultra Large Scale Integration"],
      ["UPC","Universal Product Code"],
      ["URL","Uniform Resource Locator"],
      ["USB","Universal Serial Bus"],
      ["UTF","Unicode Transformation Format"],
      ["VAN","Value Added Network"],
      ["VCR","Video Cassette Recorder"],
      ["VDT","Video Display Terminal"],
      ["VGA","Video Graphics Array"],
      ["VOD","Video-On-Demand"],
      ["VoIP","Voice over Internet Protocol"],
      ["VSAT","Very Small Aperture Terminal"],
      ["WAN","Wide Area Network"],
      ["WAP","Wireless Application Protocol"],
      ["WiMAX","Worldwide Interoperability for Microwave Access"],
      ["WLAN","Wireless Local Area Network"],
      ["WLL","Wireless Local Loop"],
      ["WORM","Write Once Read Many"],
      ["WWW","World Wide Web"],
      ["XHTML","eXtensible HyperText Markup Language"],
      ["XML","eXtensible Markup Language"],
      ["X.400","Electronic Mail Protocol"],
      ["X.500","Directory Server Protocol"],
      ["AAC","Advanced Audio Coding"],
      ["ABR","Average Bit Rate"],
      ["ADSL","Asymmetric Digital Subscriber Line"],
      ["AGP","Advanced Graphics Port"],
      ["AI","Artificial Intelligence"],
      ["AIM","AOL Instant Messenger"],
      ["ALGOL","Algorithmic Language"],
      ["ALU","Arithmetic Logic Unit"],
      ["AOL","America Online"],
      ["AMD","Advanced Micro Devices"],
      ["API","Application Program Interface"],
      ["APT","Automatically Programmed Tooling"],
      ["ARP","Address Resolution Protocol"],
      ["ARPANET","Advanced Research Projects Agency Network"],
      ["ARQ","Automatic Repeat Request"],
      ["AS","Autonomous System"],
      ["ASCII","American Standard Code for Information Interchange"],
      ["ASP","Active Server Pages"],
      ["ASPI","Advanced SCSI Programming Interface"],
      ["ATA","Advanced Technology Attachment"],
      ["ATDT","Attention Dial Tone"],
      ["AUI","Attachment Unit Interface"],
      ["AUTOEXEC","Autoexec Automatic Execution file"],
      ["AVI","Audio Video Interleave"],
      ["BCC","Blind Carbon Copy"],
      ["BCR","Bar Code Reader"],
      ["BDSL","Broadband DSL"],
      ["BEDO","Burst Extended Data Out (RAM)"],
      ["BHTML","Broadcast Hyper Text Markup Language"],
      ["BIPS","Billion Instruction Per Second"],
      ["BIU","Bus Interface Unit"],
      ["BRD","Blu-Ray Disc"],
      ["CDROM","Compact Disk Read Only Memory"],
      ["CDRW","Compact Disk Rewritable"],
      ["CD-WO","Compact Disk - Write Once"],
      ["CD-XA","Compact Disk - Extended Architecture"],
      ["CGI-BIN","Common Gateway Interface - Binary (programming for Web forms)"],
      ["CIS","CompuServe Information Service"],
      ["CISC","Complex Instructions Set Computers"],
      ["CMD","Command"],
      ["CMYK","Cyan-Magenta-Yellow-Black (color model)"],
      ["CNM","Circulatory Network Mode"],
      ["COAX","Coaxial Cable (for Ethernet and similar networks)"],
      ["COMPUTER","Commonly Operated Machine Particularly Used for Trade/Technology, Education, and Research."],
      ["CPI","Clock / Cycle Per Instruction"],
      ["CROM","Computerized Range of Motion"],
      ["CRT","Cathode Ray Tube( standard type computer monitor display"],
      ["CSLIP","Compressed Serial Line Interface Protocol (Internet)"],
      ["CSS","Cascading Style Sheets"],
      ["CTRL","Control (computer keyboard key)"],
      ["CUI","Character User Interface"],
      ["DAC","Data Acquisition and Control"],
      ["DDL","Data Definition Language"],
      ["DML","Data Manipulation Language"],
      ["DRAM","Dynamic Random Access Memory"],
      ["DVDR","Digital Versatile Disk Recordable"],
      ["DVDRW","Digital Versatile Disk Rewritable"],
      ["DCE","Data Communications Equipment"],
      ["E-Commerce","Electronic Commerce"],
      ["EDC","Electronic Digital Computer"],
      ["EDI","Electronic Data Interchange"],
      ["EDP","Electronic Data Processing"],
      ["EEPROM","Electronically Erasable Programmable Read Only Memory"],
      ["EFS","Encrypted File System"],
      ["EIDE","Enhanced Integrated Drive Electronics"],
      ["E-Mail","Electronic Mail"],
      ["EPROM","Erasable Programmable Read Only Memory"],
      ["EROM","Erasable Read Only Memory"],
      ["INTEL","Integrated Electronics"],
      ["IOP","Input Output Processor"],
    [""	  ,""],
      ["ISDN","Integrated Services Digital Network"],
      ["IVR","Interactive Voice Response"],
      ["LLL","Low Level Language"],
      ["LPT","Line Printer"],
      ["MAC","Media Access Control"],
      ["MBASIC","Microsoft BASIC (Microsoft)"],
      ["MODEM","Modulator Demodulator"],
      ["MSCDEX","Microsoft Compact Disc Extension"],
      ["NAT","Network Address Translation"],
      ["OMR","Optical Mark Reader"],
      ["PIXEL","Picture Element"],
      ["PNG","Portable Network Graphics"],
      ["PRN","Printer"],
      ["PROM","Programmable Read Only Memory"],
      ["RISC","Reduced Instruction Set Computer"],
      ["SAM","Software Asset Management"],
      ["SGML","Standard Generalized Markup Language"],
      ["SGRAM","Synchronous Graphics RAM"],
      ["SIP","Session Initiation Protocol"],
      ["SIU","Serial Interface Unit"],
      ["SNAP","Sub Network Access Protocol"],
      ["SNMP","Simple Network Management Protocol"],
      ["SRAM","Static Random Access Memory"],
      ["SYSOP","System Operator"],
      ["VCD","Video Compact Disk"],
      ["VDU","Visual Display Unit"],
      ["VIRUS","Vital Information Resource Under Siege"],
      ["VRAM","Video Random Access Memory"],
      ["VxD","Virtual Extended Driver"],
      ["WBMP","Wireless Bitmap Image"],
      ["WIFI","Wireless fidelity"],
      ["WML","Wireless Markup Language"],
      ["XGA","Extended Graphics Array"],
      ["XMF","Extensible Music File"],
      ["XMS","Extended Memory Specification"],
      ["FORTRAN","Formula Translation"],
      ["ABI","Application Binary Interface."],
      ["AD","Active Directory"],
      ["ADC","Analog – to – Digital Converter"],
      ["AHA","Accelerated Hub Architecture"],
      ["AJAX","Asynchronous JavaScript and XML"],
      ["AMR","Audio Modern Riser"],
      ["APCI","Application – Layer Protocol Control Information"],
      ["AST","Abstract Syntax Tree"],
      ["ATM"," Asynchronous Transfer Mode"],
      ["AVC","Advanced Video Coding"],
      ["AWT","Abstract WIndow ToolKit"],
      ["BAL","Basic Assembly Language"],
      ["BASIC","Beginner All-Purpose Symbolic Instruction Code"],
      ["BCD","Binary Coded Decimal"],
      ["BER","Bit Error Rate"],
      ["BFD","Binary File Descriptor"],
      ["BGP","Border Gateway Protocol"],
      ["BiDi","Bi-Directional"],
      ["BIN","Binary"],
      ["BINAC","Binary Automatic Computer"],
      ["BIOS","Basic Input Output System"],
      ["BIT","A Binary Digit"],
      ["BLOB","Binary Large Object"],
      ["BLOG","Web Log"],
      ["BPS","Bits Per Second"],
      ["BMP","Basic Multilingual Plane"],
      ["BT","BitTorrent / Bluetooth"],
      ["BW","Bandwidth"],
      ["CAD","Computer – Aided Design"],
      ["CAE","Computer – Aided Engineering"],
      ["CAI","Computer – Aided Instruction"],
      ["CAQA","Computer – Aided Quality Assurance"],
      ["CC","C Compiler / Carbon Copy"],
      ["CD","Compact Disk / Change Directory"],
      ["CDMA","Code Division Multiple Access"],
      ["CD-R","Compact Disk – Recordable"],
      ["CD-ROM"," Compact Disk – Read – Only Memory"],
      ["CD-RW"," Compact Disk – Rewritable"],
      ["CG","Computer Graphics"],
      ["CGA","Color Graphics Array"],
      ["CGI","Common Gateway Interface / Computer – Generated Imaginary"],
      ["CMOS","Complementary Metal – Oxide Semiconductor"],
      ["CIFS","Common Internet File System"],
      ["CIM","Common Information Model"],
      ["CLI","Command Line Interface"],
      ["CNC","Computer Numerical Control"],
      ["COBOL","Common Business – Oriented Language"],
      ["CPU","Central Processing Unit"],
      ["CRS","Computer Reservation System"],
      ["CTR","Cathode Ray Tube"],
      ["CSI","Common System Interface"],
      ["CSV","Comma – Separated Values"],
      ["CTCP","Client – to – Client Protocol"],
      ["CTL","Computation Tree Logic"],
      ["CTS","Clear to Send"],
      ["CUA","Common User Access"],
      ["DAO","Data Access Objects"],
      ["DAP","Direct Access Protocol"],
      ["DAT","Digital Audio Tape"],
      ["DB","DataBase"],
      ["DBA","Database Administrator"],
      ["DBMS","Database Management System"],
      ["DCC","Direct Client – to – Client"],
      ["DDR","Double Data Rate"],
      ["DES","Data Encryption Standard"],
      ["DFD","Data Flow Diagram"],
      ["DFS","Distributed File System"],
      ["DHTML","Dynamic Hyper Text Markup Language"],
      ["DIVX","Digital Video Express"],
      ["DVE","Digital Video Effects"],
      ["DLL","Dynamic Link Library"],
      ["DLP","Digital Light Processing"],
      ["DMA","Direct Memory Access"],
      ["DNS","Domain Name System"],
      ["DOS","Disk Operating System"],
      ["DPI","Dots per INCH"],
      ["DOS-PMI","Disk Operating System – Protected Mode Interface"],
      ["DSL","Digital Subscriber Line / Domain – Specific Language"],
      ["DBSN","Database Source Name (ODBC)"],
      ["DTE","Data Terminal Equipment"],
      ["DTR","Data Terminal Ready"],
      ["DVD","Digital Versatile Disk / Digital Video Disk"],
      ["DVD-R"," Digital Versatile Disk – Recordable"],
      ["DVD-ROM"," Digital Versatile Disk – Read Only Memory"],
      ["DVD-RW"," Digital Versatile Disk – Rewritable"],
      ["DVI","Digital Visual Interface"],
      ["DVR","Digital Video Recorder"],
      ["FAT","File Allocation Table"],
      ["FAQ","Frequently Asked Questions"],
      ["FDC","Floppy Disk Controller"],
      ["FDD","Floppy Disk Drive"],
      ["FDMA","Frequency-Division Multiple Access"],
      ["FIFO","First In First Out"],
      ["FHS","Filesystem Hierarchy Standard"],
      ["FCS","Frame Check Sequence"],
      ["FPU","Floating Point Unit"],
      ["FS","File System"],
      ["FSB","Front Side Bus"],
      ["FTP","File Transfer Protocol"],
      ["FXP","File Exchange Protocol"],
      ["GCR","Group Code Recording"],
      ["GDI","Graphics Device Interface"],
      ["GIF","Graphics Interchange Format"],
      ["GIGO","Garbage In Garbage Out"],
      ["GPL","General Public License"],
      ["GPRS","General Packet Radio Service"],
      ["GPU","Graphics Processing Unit"],
      ["GUI","Graphical User Interface"],
      ["HAL","Hardware Abstraction Layer"],
      ["HCI","Human Computer Interaction"],
      ["HD","High Density"],
      ["HDD","Hard Disk Drive"],
      ["HD DVD","High Definition DVD"],
      ["HDL","Hardware Description Language"],
      ["HHD","Hybrid Hard Drive"],
      ["HID","Human Interface Device"],
      ["HIG","Human Interface Guidelines"],
      ["HP","Hewlett-Packard"],
      ["HPFS","High Performance File System"],
      ["HT","Hyper Threading"],
      ["HTM","Hierarchical Temporal Memory"],
      ["HTML","Hypertext markup Language"],
      ["HTTP","Hypertext Transfer Protocol"],
      ["HTTPD","Hypertext Transfer Protocol Daemon"],
      ["HTX","Hyper Transport Expansion"],
      ["HURD","Hird of Unix-Replacing Daemons"],
      ["HVD","Holographic Versatile Disk"],
      ["HZ","Hertz"],
      ["IBM","International Business Machines"],
      ["IC","Integrated Circuit"],
      ["ICMP","Internet Control Message Protocol"],
      ["ICP","Internet Cache Protocol"],
      ["ICT","Information and Communication Technology"],
      ["IDL","Interface Definition Language"],
      ["IDE","Integrated Development Environment / Integrated Drive Electronics"],
      ["IE","Internet Explorer"],
      ["IGMP","Internet Group Management Protocol"],
      ["IGRP","Interior Gateway Routing Protocol"],
      ["IHV","Independent Hardware Vendor"],
      ["IIOP","Internet Iner-Orb-Protocol"],
      ["IIS","Internet Information Server"],
      ["IM","Instant Messaging"],
      ["IMAP","Internet Message Access Protocol"],
      ["I/O","Input / Output"],
      ["IP","Internet Protocol"],
      ["IPC","Inter-Process Communication"],
      ["IPP","Internet Printing Protocol"],
      ["IPsec","Internet Protocol Security"],
      ["IPTV","Internet Protocol Television"],
      ["IPX","Internetwork Packet Exchange"],
      ["IRC","Internet Relay Chat"],
      ["IrDA","Infrared Data Association"],
      ["IRP","I/O Request Packet"],
      ["IRQ","Interrupt Request"],
      ["ISC","Internet Storm Center"],
      ["ISO","International Organisation for Standardization"],
      ["ISOC","Internet Society"],
      ["ISP","Internet Service Provider"],
      ["ISR","Interrupt Service Routine"],
      ["ISV","Independent Software Vendor"],
      ["IT","Information Technology"],
      ["ITU","International Telecommunication Union"],
      ["J2EE","Java 2 Enterprise Edition"],
      ["J2ME","Java 2 Micro Edition"],
      ["J2SE","Java 2 Standard Edition"],
      ["JDK","Java Development KIT"],
      ["JPEG","Joint Photographic Experts Group"],
      ["JRE","Java Runtime Environment"],
      ["JS","Java Script"],
      ["JSON","Java Script Object Notation"],
      ["JSP","Java Server Pages"],
      ["JUG","Java User Group"],
      ["KHz","Kilohertz"],
      ["KBPS","Kilobit per second"],
      ["KVM","Keyboard, Video, Mouse"],
      ["LAN","Local Area Network"],
      ["LED","Light-Emitting Diode"],
      ["LIFO","Last In First Out"],
      ["LSB","Least Significant Bit"],
      ["MAN","Metropolitan Area Network"],
      ["MANET","Mobile Ad-Hoc Network"],
      ["MBCS","Multi Byte Character Set"],
      ["MBR","Master Boot Record"],
      ["MDI","Multiple Document Interface"],
      ["MICR","Magnetic Ink Character Recognition"],
      ["MIDI","Musical Instrument Digital Interface"],
      ["MIMO","Multiple-Input Multiple Output"],
      ["MIPS","Million Instructions Per Second"],
      ["MIME","Multipurpose Internet Mail Extensions"],
      ["MHz","Megahertz"],
      ["MMU","Memory Management Unit"],
      ["MMX","Multi-Media Extensions"],
      ["MNG","Multiple-image Network Graphics"],
      ["MOSFET","Metal-Oxide Semiconductor Field Effect Transistor"],
      ["MPEG","Motion Pictures (coding) Experts Group"],
      ["MPL","Mozilla Public License"],
      ["MSB","Most Significant Bit"],
      ["MS-DOS","Microsoft Disk Operating System"],
      ["MVS","Multiple Vendor System"],
      ["NFS","Network File System"],
      ["NIC","Network Interface Controller"],
      ["NIO","New I/O"],
      ["NMI","Non-Maskable Interrupt"],
      ["NNTP","Network News Transfer Protocol"],
      ["NOP","NO Operation"],
      ["NOS","Network Operating System"],
      ["NT (Windows)","New Technology"],
      ["NTFS","NT File System"],
      ["NTP","Network Time Protocol"],
      ["NVRAM","Non-Volatile Random Access Memory"],
      ["OOP","Object-Oriented Programming"],
      ["OPML","Outline Processor Markup Language"],
      ["OS","Operating System"],
      ["OSS","Open Source Software"],
      ["OCR","Optical Character Reader"],
      ["P2P","Peer-To-Peer"],
      ["PAN","Personal Area Network"],
      ["PAP","Password Authentication Protocol"],
      ["PATA","Parallel ATA"],
      ["PC","Personal Computer"],
      ["PCB","Printed Circuit Board"],
      ["PC DOS","Personal Computer Disk Operating System"],
      ["PCI","Peripheral Component Interconnect"],
      ["PCIe","PCI Express"],
      ["PCL","Printer Command Language"],
      ["PERL","Practical Extraction and Reporting Language"],
      ["PGA","Pin Grid Array"],
      ["PHP"," PHP"],
      ["PIC","Peripheral Interface Controller / Programmable Interrupt Controller"],
      ["PINE","Program for Internet News & Email"],
      ["PIO","Programmed Input/Output"],
      ["PLC","Power Line Communication / Programmable Logic Controller"],
      ["Pnp","Plug-and-Play"],
      ["PoE","Power Over Ethernet"],
      ["POST","Power-On Self Test"],
      ["PPC","Power PC"],
      ["PPI","Pixels Per Inch"],
      ["PPP","Point-to-Point Protocol"],
      ["PPPoA","PPP over ATM"],
      ["PPPoE","PPP over Ethernet"],
      ["PPTP"," Point-to-Point Tunneling Protocol"],
      ["PSU"," Power Supply Unit"],
      ["QDR","Quad Data Rate"],
      ["QoS","Quality of Service"],
      ["QFP","Quick File Access"],
      ["RAD","Rapid Application Development"],
      ["RADIUS","Remote Authentication Dial In User Service"],
      ["RAID","Redundant Array of Independent Disks"],
      ["RAIT","Redundant Array of Inexpensive Tapes"],
      ["RAM","Random Access Memory"],
      ["RARP","Reverse Address Resolution Protocol"],
      ["RDBMS","Relation Database Management System"],
      ["RDF","Resource Description Framework"],
      ["REEAL","Recursive Functions Algorithmic Language"],
      ["RF","Radio Frequency"],
      ["RGB","Red, Green, Blue (RGBA- Red, Green, Blue, Alpha)"],
      ["RIP","Routing Information Protocol"],
      ["ROM","Read Only Memory"],
      ["ROMB","Read-Out Motherboard"],
      ["ROM-DOS","Read Only Memory-Disk Operating System"],
      ["RTOS","Real Time Operating System"],
      ["SAN","Storage Area Network"],
      ["SATA","Serial ATA"],
      ["SAX","Simple API of XML"],
      ["SBP-2","Serial Bus Protocol 2"],
      ["SBU","  Standard Build Unit"],
      ["SCSI","Small Computer System Interface"],
      ["SDL","Simple Direct Media Layer"],
      ["SDN","Service Delivery Network"],
      ["SDR","Software-Defined Radio"],
      ["SDRAM","Synchronous Dynamic Random Access Memory"],
      ["SFTP","Secure FTP/Simple File Transfer Protocol"],
      ["SHDSL","Single-pair High-speed Digital Subscriber Line"],
      ["SIMD","Single Instruction, Multiple Data"],
      ["SIMM","Single InLine Memory Module"],
      ["SMBIOS","System Management BIOS"],
      ["SMTP","Simple Mail Transfer Protocol"],
      ["SP","Service Pack"],
      ["SPI","Serial Peripheral Interface"],
      ["SQL","Structured Query Language"],
      ["SUS","Single UNIX Specification"],
      ["SVD","Structured VLSI Design"],
      ["SVG","Scalable Vector Graphics"],
      ["SVGA","Super Video Graphics Array"],
      ["TB","TeraByte"],
      ["TCP","Transmission Control Protocol"],
      ["TCP/IP","Transmission Control Protocol / Internet Protocol"],
      ["TDMA","Time Division Multiple Access"],
      ["tmp","Temporary"],
      ["TTA","True Tap Audio"],
      ["TTF","True Type Font"],
      ["TTL","Transistor-Transistor-Logic"],
      ["TTS","Text-to Speech"],
      ["TTY","Teletype"],
      ["UAC","User Account Control"],
      ["UART","Universal Asynchronous Receiver Transmitter"],
      ["UEFI","Unified Extensible Firmware Interface"],
      ["UI","User Interface"],
      ["UL","Upload"],
      ["UPS","Uninterruptible Power Supply"],
      ["URI","Uniform Resource Identifier"],
      ["URL","Uniform Resource Locator"],
      ["URN","Uniform Resource Name"],
      ["USB","Universal Serial Bus"],
      ["UTF","Unicode Transformation Format"],
      ["UTP","Unshielded Twisted Pair"],
      ["VAR","Variable"],
      ["VB","Visual Basic"],
      ["VBA","Visual Basic for Applications"],
      ["VBS","Visual Basic Script"],
      ["VFAT","Virtual FAT"],
      ["VFS","Virtual File System"],
      ["VGA","Video Graphics Array"],
      ["VGCT","Video Graphics Character Table"],
      ["VLAN","Virtual Local Area Network"],
      ["VM","Virtual Memory"],
      ["VOD","Video On Demand"],
      ["VoIP","Voice Over IP"],
      ["VPN","Virtual Private Network"],
      ["VPU","Visual Processing Unit"],
      ["VT","Video Terminal"],
      ["WAN","Wide Area Network"],
      ["WAP","Wireless Access Protocol"],
      ["Wi-Fi","Wireless Fidelity"],
      ["WinFS","Windows Future Storage"],
      ["WINS","Windows Internet Naming Service"],
      ["WLAN","Wireless Local Area Network"],
      ["WMA","Windows Media Audio"],
      ["WMV","Windows Media Video"],
      ["WOL","Wake-on-Lan"],
      ["WOM","Wake-on-Modem"],
      ["WPA","Wi-Fi Protected Access"],
      ["WSDL","Web Services Description Language"],
      ["WUSB","Wireless Universal Serial Bus"],
      ["WWAN","Wireless Wide Area Network"],
      ["WWID","World Wide Identifier"],
      ["WWW","World Wide Web"],
      ["XAML","Extensible Application Merkup Language"],
      ["XHTML","Extensible Hypertext Markup Language"],
      ["XML","Extensible Markup Language"],
      ["XNS","Xerox Network Services"],
      ["XMMS","X MultiMedia System"],
      ["XSL","Extensible StyleSheet Language"],
      ["XSL-FO","Extensible StyleSheet language Formatting Objects"],
      ["XSLIT"," Extensible StyleSheet language Transformations"],
      ["XUL","XML User Interface Language"],
      ["ZIFS","Zero Insertion Force Socket"],
      ["ZISC","Zero Instruction Set Computer"],
      ["ZMA","ZMA"],
    ["A11Y","Accessibility"],
    ["ABAC","Attribute-Based Access Control"],
    ["AC","Alternating Current"],
    ["ACI","Azure Container Instance"],
    ["ACL","Access Control List"],
    ["ACM","AWS Certificate Manager"],
    ["ACR","Azure Container Registry"],
    ["AD","Active Directory"],
    ["ADC","Analog to Digital Converter"],
    ["ADC","AWS Direct Connect Amazon"],
    ["AEAD","Authenticated Encryption with Associated Data"],
    ["AES","Advanced Encryption Standard"],
    ["AHOD","All Hands On Deck"],
    ["AI","Artificial Intelligence"],
    ["AIS","Automated Indicator Sharing"],
    ["AICPA","Association of International Certified Professional Accountants"],
    ["AKA","Also Known As"],
    ["AKS","Azure Kubernetes Service"],
    ["AKV","Azure Key Vault"],
    ["ALB","Application Load Balancer"],
    ["ALE","Annualized Loss Expectancy"],
    ["ALEER","Adopt Land Ex pand Extend Renew"],
    ["ALM","Application Lifecycle Management"],
    ["AM","Account Manager"],
    ["AMA","Ask Me Anything"],
    ["AMA","Azure Marketplace Application"],
    ["AMI","Amazon Machine Image"],
    ["AMQP","Advanced Message Queuing Protocol"],
    ["AO","Authorizing Official"],
    ["API","Application Programming Interface"],
    ["APJ","Asia + Pacific + Japan"],
    ["APM","Application Performance Monitoring"],
    ["APT","Advanced Persistent Threat"],
    ["ARG","Azure Resource Graph"],
    ["ARM","Advanced RISC Machine"],
    ["ARN","Amazon Resource Name"],
    ["ARO","Annual Rate of Occurrence"],
    ["ARP","Address Resolution Protocol"],
    ["ARR","Annual Recurring Revenue"],
    ["ASC","Azure Security Center"],
    ["ASG","Auto Scaling Groups"],
    ["ASIC","Application-Specific Integrated Circuit"],
    ["ASIM","Advanced Security Information Model"],
    ["ASM","AWS Secrets Manager"],
    ["ASN","Autonomous System Number."],
    ["ASO","Azure Service Operator"],
    ["ATA","Advanced Threat Analytics"],
    ["ATARC","Advanced Technology Academic Research Center"],
    ["ATO","Authority To Operate"],
    ["AuthN","Authentication"],
    ["AuthZ","Authorization"],
    ["AWS","Amazon Web Services"],
    ["B2B","Business to Business"],
    ["B2C","Business to Consumer"],
    ["BANT","Budget + Authority + Need + Timeframe"],
    ["BAU","Business Administration Unit"],
    ["BBS","BitBucket Server"],
    ["BCDR","Business Continuity and Disaster Recovery"],
    ["BCP","Business Continuity Plan"],
    ["BDM","Business Decision Maker"],
    ["BDR","Business Development Representative"],
    ["BEC","Business Email Compromise"],
    ["BGP","Border Gateway Protocol"],
    ["BHAG","Big Hairy Audacious Goal"],
    ["BIA","Business Impact Assessment"],
    ["BIOS","Basic Input Output System"],
    ["BKM","Best Known Method"],
    ["BLE","Bluetooth Low Energy"],
    ["BOM","Bill of Material"],
    ["BPMN","Business Process Model Notation"],
    ["BRB","Be Right Back"],
    ["BRM","Business Requirements Management"],
    ["BTP","Behavioral Threat Protection"],
    ["BTW","By The Way"],
    ["BU","Business Unit"],
    ["BVA","Business Value Assessment"],
    ["BYOIP","Bring Your Own IP address"],
    ["BYOK","Bring Your Own Key"],
    ["C2E","Commercial Cloud Enterprise"],
    ["CA","Certificate Authority"],
    ["CaC","Configuration as Code"],
    ["CAF","Cloud Adoption Framework"],
    ["CAGR","Compound Annual Growth Rate"],
    ["CAI","Cloud Asset Inventory"],
    ["CAIQ","Consensus Assessments Initiative Questionnaire"],
    ["CAM","Corporate Account Manager"],
    ["CAP","Common Alerting Protocol"],
    ["CAP","Cybersecurity Assessment Plan"],
    ["CAPEX","Capital Expenditures"],
    ["CAPTCHA","Completely Automated Public Turing"],
    ["CASB","Cloud Access Security Broker"],
    ["CBK","Common Body of Knowledge"],
    ["CCB","Change Control Board"],
    ["CCE","Critical Customer Escalation"],
    ["CCM","Cloud Controls Matrix"],
    ["CCM","Continuous Controls Monitoring"],
    ["CCM","Customer Communications Management"],
    ["CCP","Common Control Provider"],
    ["CCP","Crisis Communication Plan"],
    ["CCS","Complete Corresponding Source"],
    ["CCTV","Closed-circuit TeleVision"],
    ["CDK","Cloud Development Kit"],
    ["CDM","Continuous Diagnostics and Mitigation"],
    ["CDN","Content Distribution Network"],
    ["CDPI","Control Data-Plane Interface"],
    ["CEO","Chief Executive Officer"],
    ["CfCT","Customizations for Control Tower Amazon"],
    ["CD","Continuous Deployment"],
    ["CE","Community Edition"],
    ["CF","CloudFormation"],
    ["CFAA","Computer Fraud & Abuse Act"],
    ["CFT","Cloud Foundation Toolkit"],
    ["CI","Continuous Integration"],
    ["CIAN","Customer Identity and Access Management"],
    ["CIDR","Classless Inter-Domain Routing"],
    ["CIEM","Cloud Infrastructure and Entitlement Management"],
    ["CIM","Common Information Model"],
    ["CIP","Critical Infrastructure Protection"],
    ["CIRP","Cyber Incident Response Plan"],
    ["CIS","Center for Internet Security"],
    ["CISA","Cybersecurity and Infrastructure Security Agency"],
    ["CISO","Chief Information Security Officer"],
    ["CKL","Compromised Key List"],
    ["CKMS","Cryptographic Key Management System"],
    ["CLI","Command Line Interface"],
    ["CMK","Customer-Managed Key"],
    ["CMP","Cloud Management Platform"],
    ["CN","Common Name"],
    ["CNAME","Canonical Name Record"],
    ["CNI","Container Network Interface"],
    ["CMDB","Configuration Management Database"],
    ["CNSS","Committee on National Security Systems"],
    ["COGS","Cost of Goods Sold"],
    ["COOP","Continuity of Operations"],
    ["COSO","Committee of Sponsoring Organization"],
    ["COTS","Commercial Off-The-Shelf"],
    ["CPA","Certified Public Accountant"],
    ["CPIC","Capital Planning Investment Controls"],
    ["CPU","Central Processing Unit"],
    ["CRD","Custom Resource Definition"],
    ["CRI","Container Runtime Interface"],
    ["CRR","Cross-Region Replication"],
    ["CRL","Certificate Revocation List"],
    ["CRM","Customer Relationship Management"],
    ["CRR","Cyber Resilience Review"],
    ["CRT","Common Release Tooling"],
    ["CS","Customer Success"],
    ["CSA","Cloud Security Alliance"],
    ["CSAF","Common Security Advisory Framework"],
    ["CSB","Cloud Service Broker"],
    ["CSC","Cloud Service Customer"],
    ["CSC","Critical Security Controls"],
    ["CSE","Customer Success Engineer"],
    ["CSF","Cyber Security Framework"],
    ["CSI","Container Storage Interface"],
    ["CSM","Customer Success Manager"],
    ["CSP","Cloud Service Provider"],
    ["CSP","Cryptographic Service Provider"],
    ["CSPM","Cloud Security Posture Management"],
    ["CSQL","Customer Success Qualified Lead"],
    ["CSR","Certificate Signing Request"],
    ["CTA","Call To Action"],
    ["CTAP","Client To Authenticator Protocol"],
    ["CTF","Cyber Threat Framework"],
    ["CTI","Cyber Threat Intelligence"],
    ["CTO","Chief Technology Officer"],
    ["CTS","Consul-Terraform Sync"],
    ["CVE","Common Vulnerabilities and Exposures"],
    ["CVRF","Common Vulnerability Reporting Framework"],
    ["CVSS","Common Vulnerability Scoring System"],
    ["CWE","Common Weakness Enumerations"],
    ["CWPP","Cloud Workload Protection Platform"],
    ["DaaS","Data as a Service"],
    ["DA","Developer Advocate"],
    ["DAC","Discretionary Access Control"],
    ["DART","Detection and Response Team"],
    ["DB","Database"],
    ["DC","Data Center"],
    ["DC","Domain Controller"],
    ["DCAP","Data-Centric Audit Protection"],
    ["DDD","Domain Driven Design"],
    ["DDoS","Distributed Denial of Service Attack"],
    ["DEK","Data Encryption Key"],
    ["DEI","Diversity + Equity + Inclusion"],
    ["DES","Digital Encryption Standard"],
    ["DFIR","Digital Forensics and Incident Response"],
    ["DHCP","Dynamic Host Configuration Protocol"],
    ["DHS","Department of Homeland Security"],
    ["DLP","Data Loss Prevention"],
    ["DMZ","Demilitarized Zone"],
    ["DNC","Do Not Connect"],
    ["DNS","Domain Name Service"],
    ["DOD","Department of Defense"],
    ["DODAF","Department of Defense Architecture Framework"],
    ["DPIA","Data Protection Impact Assessment"],
    ["DR","Disaster Recovery"],
    ["DRI","Directly Responsible Individual"],
    ["DRP","Disaster Recovery Plan"],
    ["DRPO","Defense Research & Development Organization"],
    ["DRY","Don’t Repeat Yourself"],
    ["DSC","Digital Signature Algorithm"],
    ["DTC","Diagnostic Trouble Code"],
    ["DTLS","Datagram Transport Layer Security"],
    ["DUT","Device Under Test"],
    ["DX","Developer eXperience"],
    ["E2E","End-to-End"],
    ["EA","Enterprise Architect"],
    ["EAL","Evaluation Assurance Level"],
    ["EAM","Externalized Authorization Management"],
    ["EAP","Extensible Authentication Protocol"],
    ["EAR","Export Administration Regulations"],
    ["EBS","Elastic Block Store"],
    ["ECDSA","Elliptic Curve Digital Signature Algorithm"],
    ["EDI","Electronic Data Interchange"],
    ["EE","Enterprise Edition"],
    ["EIN","Employer Identification Number"],
    ["EC2","Elastic Cloud Compute"],
    ["ECR","Elastic Container Registry"],
    ["ECS","Elastic Container Service"],
    ["ECU","EC2 compute unit"],
    ["EDA","Event Driven Architecture"],
    ["EDM","External Dependency Management"],
    ["EDR","Endpoint Detection and Remediation"],
    ["EFS","Elastic File System"],
    ["EFT","Electronic Funds Transfer"],
    ["ELA","Enterprise License Agreement"],
    ["EMR","Elastic Map Reduce"],
    ["EKM","Extensible Key Management"],
    ["EKS","Elastic Kubernetes Service"],
    ["ELB","Elastic Load Balancer"],
    ["EMEA","Europe + Middle East + Africa"],
    ["EMI","Electro-Magnetic Interference"],
    ["ENI","Elastic Network Interface"],
    ["EPS","Earnings Per Share"],
    ["ETL","Extract Transform and Load"],
    ["EOQ","End of Quarter"],
    ["EOM","End of Month"],
    ["EO","Executive Order"],
    ["EOP","Exchange Online Protection"],
    ["EOY","End of Year"],
    ["ERM","Enterprise Risk Management"],
    ["ERP","Enterprise Resource Planning"],
    ["EU","European Union"],
    ["EV","Extended Validation"],
    ["FBL","Feedback Loop"],
    ["FDE","Full Disk Encryption"],
    ["FEA","Federal Enterprise Architecture"],
    ["FEDRAMP","Federal Risk and Authorization Management Program"],
    ["FHRP","First Hop Redundancy Protocol"],
    ["FIDO2","Fast IDentity Online"],
    ["FIFO","First In - First Out"],
    ["FIM","Federated Identity Management"],
    ["FIM","File Integrity Monitoring"],
    ["FN","False Negative"],
    ["FOMO","Fear Of Missing Out"],
    ["FP","False Positive"],
    ["FQDN","Fully-qualified Domain Name"],
    ["FTE","Full Time Employee/Equivalent"],
    ["FQDN","Fully Qualified Domain Name"],
    ["FSM","Finite State Machine"],
    ["FYE","Fiscal Year End"],
    ["FUD","Fear Uncertainty and Doubt"],
    ["GAPP","Generally Accepted Privacy Principles"],
    ["GA","General Availability"],
    ["GAI","Generative Artificial Intelligence"],
    ["GAM","Global Account Manager"],
    ["GB","Gigabytes"],
    ["GCE","Google Compute Engine"],
    ["GCP","Google Cloud Platform"],
    ["GCM","Galois/Counter Mode"],
    ["GDPR","General Data Protection Regulation"],
    ["GHA","GitHub Actions"],
    ["GID","Group Identifier"],
    ["GKE","Google Kubernetes Engine"],
    ["GKS","Google Kubernetes Service"],
    ["GLB","Global Load Balancing"],
    ["GNM","Global Network Manager"],
    ["GNU","GNU is Not Unix"],
    ["GPG","GNU Privacy Guard"],
    ["GPS","Global Positioning System"],
    ["GPT","GUID Partition Table"],
    ["GRC","Governance and Risk and Compliance"],
    ["gRPC","Global Remote Procedure Call"],
    ["GSI","Global System Integrator"],
    ["GTM","Go To Market"],
    ["GUI","Graphical User Interface"],
    ["GW","Gateway"],
    ["H2M","Human to Machine"],
    ["HA","High Availability"],
    ["HC","HashiCorp"],
    ["HCL","HashiCorp Configuration Language"],
    ["HD","High Definition"],
    ["HEC","HTTP Event Collector"],
    ["HCM","Human Capital Management"],
    ["HCP","HashiCorp Cloud Provider"],
    ["HCS","HashiCorp Consul Service"],
    ["HIPAA","Health Insurance Portability and Accountability Act"],
    ["HiPPO","Highest Paid Person‚Äôs Opinions"],
    ["HMI","Human-Machine Interface"],
    ["HPA","HorizontalPodAutoscaler"],
    ["HPC","High-Performance Compute"],
    ["HR","Human Resources"],
    ["HSM","Hardware Security Module"],
    ["HTML","HyperText Markup Language"],
    ["HTTPS","HyperText Transfer Protocol Secure"],
    ["HVA","High-Value Asset"],
    ["HVN","HashiCorp Virtual Network"],
    ["I18N","Internationalization"],
    ["IA","Interoperability Agreement"],
    ["IaaS","Infrastructure as a Service"],
    ["IaC","Infrastructure as Code"],
    ["IAB","Internet Architecture Board"],
    ["IAM","Identity and Access Management"],
    ["IAP","Identity-Aware Proxy"],
    ["IASAE","Information Assurance Security Architecture and Engineering"],
    ["IAST","Interactive Application Security Testing"],
    ["IBN","Internet-based Networking"],
    ["IC","Integrated Circuit"],
    ["ICFR","Internal Control over Financial Reporting"],
    ["ICMP","Internet Control Message Protocol"],
    ["ICS","Industrial Control System"],
    ["ICT","Information and Communication Technology"],
    ["ICYMI","In Case You Missed It"],
    ["ID","Identifier"],
    ["IDaaS","Identity as a Service"],
    ["IDE","Integrated Development Environment"],
    ["IDOR","Insecure Direct Object Reference"],
    ["IdP","Identity Provider"],
    ["IDP","Internal Developer Platform"],
    ["IDS","Intrusion Detection System"],
    ["IEM","Infrastructure Event Management"],
    ["IETF","Internet Engineering Task Force"],
    ["IGA","Identity Governance and Administration"],
    ["IIoT","Industrial Internet of Things"],
    ["ILT","Instructor-Led Training"],
    ["IM","Internet Messaging"],
    ["IOCs","Indicators of Compromise"],
    ["IOPS","Input Output Per Second"],
    ["IOT","Internet of Things"],
    ["IP","Internet Protocol"],
    ["IPAM","IP Address Manager"],
    ["IPE","Information Produced by the Entity"],
    ["IPS","Intrusion Protection System"],
    ["IPsec","Internet Protocol security"],
    ["IPO","Initial Public Offering"],
    ["IRL","In Real Life"],
    ["IRM","Information Rights Management"],
    ["IRT","Incident Response Team"],
    ["ISCP","Information System Contingency Plan"],
    ["ISMS","Information Security Management System"],
    ["ISO","International Standards Organization"],
    ["ISSO","Information System Security Officer"],
    ["ISP","Internet Service Provider"],
    ["ISV","Independent Software Vendor"],
    ["IT","Information Technologies"],
    ["ITAR","International Traffic in Arms Regulations"],
    ["ITIL","Information Technology Infrastructure Library"],
    ["ITSM","IT Service Management"],
    ["ITU","International Telecommunication Union"],
    ["JIT","Just-In-Time"],
    ["JEA","Just-Enough-Access"],
    ["JSON","JavaScript Notation"],
    ["JWT","JSON Web Token"],
    ["K8s","Kubernetes"],
    ["kanban","Japanese word for visual signal"],
    ["KDC","Key Distribution Center"],
    ["KEK","Key Encryption Key"],
    ["KMIP","Key Management Interoperability Protocol"],
    ["KMS","Key Management Service"],
    ["KPI","Key Performance Indicator"],
    ["KTS","Kubernetes Threat Detection"],
    ["KRI","Key Recovery Information"],
    ["KV","Key-Value"],
    ["KYC","Know Your Customer"],
    ["LAMP","Linux OS + Apache web server + MySQL DB + PHP/Perl/Python"],
    ["L18N","Localization"],
    ["LAN","Local Area Network"],
    ["LDAP","Lightweight Directory Access Protocol"],
    ["LI","Lead Implementer"],
    ["LIFO","Last In - Last Out"],
    ["LLC","Limited Liability Company"],
    ["LLM","Large Language Model"],
    ["LMS","Learning Management System"],
    ["LTM","Last Twelve Months"],
    ["LUN","Logical Unit Number"],
    ["MAC","Media Access Control"],
    ["MAC","Message Authentication Code"],
    ["MAP","Minimum Acceptable Product"],
    ["MEF","Mission Essential Functions"],
    ["MBR","Master Boot Record"],
    ["MCSB","Microsoft Cybersecurity Security Benchmark"],
    ["MCRA","Microsoft Cybersecurity Reference Architectures"],
    ["MDTI","Microsoft Defender Threat Intelligence"],
    ["MDM","Mobile Device Management"],
    ["MFA","Multi-Factor Authentication"],
    ["MIG","Managed Instance Group"],
    ["MIT","Most Important Task"],
    ["MitB","Man-in-the-Browser"],
    ["MitM","Man-in-the-Middle"],
    ["ML","Machine Learning"],
    ["MS","Microsoft"],
    ["MSA","Master Service Agreement"],
    ["MSI","Managed Service Identity"],
    ["MTD","Month-To-Date"],
    ["mTLS","Mutual TLS"],
    ["MOR","Minimum Operating Requirements"],
    ["MSI","Microsoft Software Installer"],
    ["MTD","Maximum Tolerable Downtime"],
    ["MQTT","MQ Telemetry Transport"],
    ["MSAL","Microsoft Authentication Libraries"],
    ["MSP","Managed Service Provider"],
    ["MSSP","Managed Security Service Provider"],
    ["MTA","Mail Transfer Agent"],
    ["MTTA","Mean Time To Acknowledge"],
    ["MTTD","Mean Time To Detect"],
    ["MTTR","Mean Time To Restore/Remediate"],
    ["MTU","Maximum Transmission Unit"],
    ["MVP","Minimum Viable Product"],
    ["MY","Multi-Year"],
    ["NAC","Network Admission Control/Controller"],
    ["NAD","Network Access Devices"],
    ["NAT","Network Address Translation"],
    ["NB","No Problem"],
    ["NDA","Non-Disclosure Agreement"],
    ["NDAA","National Defense Authorization Act of 2020 and 2021"],
    ["NDE","Net Dollar Expansion"],
    ["NDRR","Net Dollar Retention Rate"],
    ["NFR","Non-Functional Requirements"],
    ["NFS","Network File System"],
    ["NGFW","Next-Generation firewall"],
    ["NIA","Network Interface"],
    ["NIACAP","National Information Assurance Certification and Accreditation Process"],
    ["NIAP","National Information Assurance Partnership"],
    ["NIC","National Interface Card"],
    ["NIST","National Institute of Standards and Technology"],
    ["NLB","Network Load Balancer"],
    ["NPS","Net Promoter Score"],
    ["NSG","Network Security Group"],
    ["NTA","Network Traffic Anomaly"],
    ["NTM","Next Twelve Months"],
    ["NTP","Network Time Protocol"],
    ["NVD","National Vulnerability Database"],
    ["OCI","Container Open Initiative"],
    ["OCSP","Online Certificate Status Protocol"],
    ["OCM","Organizational Change Management"],
    ["ODNI","Office of the Director of National Intelligence"],
    ["OEM","Original Equipment Manufacturer"],
    ["OEP","Occupant Emergency Plan"],
    ["OKR","Objective and Key Results"],
    ["OLAP","OnLine Analytical Processing"],
    ["OKR","Objectives and Key Results"],
    ["OIDC","OpenID Connect"],
    ["OOP","Object Oriented Programming"],
    ["OPA","Open Policy Agent"],
    ["OPEX","Operating Expenditures"],
    ["OS","Operating System"],
    ["OSCAL","Open Security Controls Assessment Language"],
    ["OSCP","Online Certificate Status Protocol"],
    ["OSINT","Open Source Intelligence"],
    ["OSS","Open Source Software"],
    ["OT","Operational Technology"],
    ["OTP","One-Time Password"],
    ["OVAL","Open Vulnerability and Assessment Language"],
    ["OU","Organizational Unit"],
    ["OWASP","Open Web Application Security Project"],
    ["PaaS","Platform as a Service"],
    ["PaC","Policy as Code"],
    ["PAM","Privileged Access Management"],
    ["PASTA","Process for Attack Simulation and Threat Analysis"],
    ["PAT","Port Address Translation"],
    ["PAW","Privileged Access Workstation"],
    ["PAYG","Pay-As-You-Go"],
    ["PBC","Provided By Client"],
    ["PC","Personal Computer"],
    ["PCI","Peripheral Components Interconnect"],
    ["PCI DSS","Payment Card Industry Data Security Standard"],
    ["PDD","Project Delivery Document"],
    ["PDF","Portable Document Format"],
    ["PEP","Policy Enforcement Point"],
    ["PFS","Perfect Forward Secrecy"],
    ["PHI","Protected Health Information"],
    ["PHS","Password Hash Synchronization"],
    ["PID","Process Identifier"],
    ["PII","Personally Identifiable Information"],
    ["PIM","Privileged Identity Management"],
    ["PIN","Personal Identification Number"],
    ["PIV","Personal Identity Verification"],
    ["PKI","Public Key Infrastructure"],
    ["PM","Product Management/Manager"],
    ["P&L","Profit and Loss"],
    ["PMM","Product Marketing Manager"],
    ["PMO","Program Management Office"],
    ["POA&M","Plan of Action and Milestones"],
    ["PoC","Proof of Concept"],
    ["POLP","Principle of Least Privilege"],
    ["POM","Production Operations Management"],
    ["POR","Process of Record"],
    ["PPTP","Point-to-Point Tunneling Protocol"],
    ["PR","Pull Request"],
    ["PS","Professional Services"],
    ["PSE","Professional Services Engineer"],
    ["PSIRT","Product Security Incident Response Team"],
    ["PSK","Pre-Shared Key"],
    ["PTA","Pass-Through Authentication"],
    ["PUA","Potentially Unwanted Application"],
    ["PV","Persistent Volume"],
    ["PVC","Persistent Volume Claim"],
    ["PWC","Price Waterhouse Coopers"],
    ["QA","Quality Assurance"],
    ["QBR","Quarterly Business Review"],
    ["QKD","Quantum Key Distribution"],
    ["QoQ","Quarter on Quarter"],
    ["QoS","Quality of Service"],
    ["RACI","Responsible + Accountable + Consulted + Informed"],
    ["RAID","Redundant Array of Independent Disks"],
    ["RAM","Random Access Memory"],
    ["RASP","Runtime Application Self-Protection"],
    ["RAT","Remote Access Trojan"],
    ["RBAC","Role-Based Access Control"],
    ["RBG","Random Bit Generator"],
    ["RCA","Root Cause Analysis"],
    ["RCE","Root Code Execution"],
    ["RDP","Remote Desktop Protocol"],
    ["RDS","Relational Database Service"],
    ["REST","Representational State Transfer"],
    ["RFI","Request for Information"],
    ["RFP","Request for Proposal"],
    ["RFQ","Request for Quote"],
    ["RGB","Red Green Blue"],
    ["RGDD","Reliable Group Data Delivery"],
    ["RISC","Reduced Instruction Set Computing"],
    ["RMF","Risk Management Framework"],
    ["ROA","Return on Assets"],
    ["ROC","Report on Compliance"],
    ["ROE","Return on Equity"],
    ["ROI","Return on Investment"],
    ["ROM","Read-only Memory"],
    ["ROS","Return on Sales"],
    ["RPA","Robotic Process Automation"],
    ["RPC","Remote Procedure Call"],
    ["RPO","Recovery Point Objective"],
    ["RPS","Requests Per Second"],
    ["RRA","Rapid Risk Assessment"],
    ["RSA","Resident System Engineer"],
    ["RSA","Rivest + Shamir + Adleman"],
    ["RTC","Real Time Clock"],
    ["RTO","Recovery Time Objective"],
    ["RUM","Resources Under Management"],
    ["RaMP","Rapid Modernization Plan"],
    ["S3","Simple Storage Service"],
    ["SaaS","Software as a Service"],
    ["SAML","Security Assertion Markup Language"],
    ["SAP","Systems Applications and Product"],
    ["SAP","System Assessment Plan"],
    ["SAQ","Self-Assessment Questionaire"],
    ["SAR","Security Assessment Report"],
    ["SARs","System Assessment Results"],
    ["SASE","Secure Access Service Edge"],
    ["SAST","Static Application Security Testing"],
    ["SBOM","Software Bill of Materials"],
    ["SCA","Software Composition Analysis"],
    ["SCADA","Supervisory Control And Data Acquisition"],
    ["SCC","Security Command Center"],
    ["SCEP","Simple Certificate Enrollment Protocol"],
    ["SCM","Source Control Manager"],
    ["SCP","Service Control Policies"],
    ["SCSS","Sidecar Container Security Stack"],
    ["SEB","Secure Enterpise Browsers"],
    ["SDK","Software Development Kit"],
    ["SDN","Software-Defined Networking"],
    ["SDLC","System Development Life Cycle"],
    ["SDMN","Software-defined Mobile Network"],
    ["SDP","Software Defined Perimeter"],
    ["SES","Simple Email Service"],
    ["SF","Service Fabric"],
    ["SHA","Secure Hash Algorithm"],
    ["SI","Systems Integrator"],
    ["SIEM","Security Information and Event Management"],
    ["SIG","Special Interest Group"],
    ["SIRT","Security Incident Response Team"],
    ["SLA","Service Level Agreement"],
    ["SLE","Single Loss Expectancy"],
    ["SLI","Service Level Indicator"],
    ["SLO","Service Level Objective"],
    ["SLSA","Supply chain Levels for Software Artifacts"],
    ["SME","Subject Matter Expert"],
    ["SMI","Service Mesh Interface"],
    ["SNMP","Simple Network Management Protocol"],
    ["SMaaS","Service Mesh as a Service"],
    ["SMTP","Simple Mail Transfer Protocol"],
    ["SNS","Simple Notification Service"],
    ["SOAP","Simple Object Access Protocol"],
    ["SOC","Security Operations Center"],
    ["SOC2","Systems and Organization Controls"],
    ["SOA","Service Oriented Architecture"],
    ["SOP","Standard Operating Procedure"],
    ["SORN","System of Record Notice"],
    ["SOX","Sarbanes-Oxley Act"],
    ["SQL","Structured Query Language"],
    ["SPI","Service Provider Interface"],
    ["SPIFFE","Secure Production Identity Framework for Everyone"],
    ["SPLK","Splunk’s stock ticker symbol"],
    ["SQS","Simple Queue Service"],
    ["SOAR","Security Orchestration Automation and Response"],
    ["SOW","Statement of Work"],
    ["SPI","Secure Personal Information"],
    ["SPOC","Single Point of Contact"],
    ["SPOF","Single Point of Failure"],
    ["SPSCR","Security, Privacy, and Supply Chain Risks"],
    ["SRA","Security Reference Architecture"],
    ["SRE","Site Reliability Engineer"],
    ["SSAE","Statement on Standards for Attestation Engagements"],
    ["SSD","Solid-State Drive"],
    ["SSE","Security Service Edge"],
    ["SSE","Server-Side Encryption"],
    ["SSDLC","Secure Software Development Lifecycle"],
    ["SSH","Secure Shell"],
    ["SSI","Sensitive Security Information"],
    ["SSL","Secure Sockets Layer"],
    ["SSN","Social Security Number"],
    ["SSO","Single Sign On"],
    ["SSP","System Security Plan"],
    ["SSRF","Server Side Request Forgery"],
    ["SSRM","Shared Security Responsibility Model"],
    ["STIX","Structured Threat Information eXpression"],
    ["STRIDE","Spoofing of user identity; Tampering; Repudiation; Information disclosure"],
    ["STS","Security Token Service"],
    ["STS","StatefulSets"],
    ["SUT","System Under Test"],
    ["SVID","SPIFFE Verifiable Identity Document"],
    ["SWG","Secure Web Gateway"],
    ["TAM","Total Addressable Market"],
    ["TAXII","Trusted Automated eXchange of Intelligence Information"],
    ["TB","TerraByte"],
    ["TBD","To Be Decided"],
    ["TDE","Transparent Data Encryption"],
    ["TDM","Technical Decision Maker"],
    ["TFC","Terraform Cloud"],
    ["TFE","Terraform Enterprise"],
    ["TIC","Trusted Internet Connection"],
    ["TIN","Tax Identification Number"],
    ["TCSEC","Trusted Computer System Evaluation Criteria"],
    ["TCO","Total Cost of Ownership"],
    ["TDD","Test-Driven Development"],
    ["TDM","Technical Decision Maker"],
    ["TFE","Terraform Enterprise"],
    ["TGW","Transit GateWay"],
    ["TH","Threat Hunting"],
    ["TIP","Threat Intelligence Platform"],
    ["TLD","Top Level Domain"],
    ["TLS","Transport Layer Security"],
    ["TMI","Too Much Information"],
    ["TOE","Target of Evaluation"],
    ["TOFU","Trust On First Use"],
    ["TOTP","TIme-based One Time Password"],
    ["TPISRM","Third Party Information Security Risk Management"],
    ["TPM","Trusted Platform Module"],
    ["TPRM","Third Party Risk Management"],
    ["TSC","Trust Service Criteria"],
    ["TSI","Trustworthy Software Initiative"],
    ["TTL","Time to Value"],
    ["TTL","Time To Live"],
    ["TTP","Trusted Third Party"],
    ["TTP","Tactics, Techniques, Procedures"],
    ["TTS","Text To Speech"],
    ["TVM","Threat and Vulnerability Management"],
    ["UAC","User Account Control"],
    ["UAT","User Acceptance Test"],
    ["UCS","User"],
    ["UDS","Unified Diagnostic Services"],
    ["UEBA","User and Entity Behavior Analytics"],
    ["UEFI","Unified Extensible Firmware Interface"],
    ["UEM","Unified Endpoint Management/Manager"],
    ["UDP","User Datagram Protocol"],
    ["UML","Unified Modeling Language"],
    ["UPN","User Principal Name"],
    ["URI","Universal Resource Identifier"],
    ["URL","Universal Resource Locator"],
    ["URM","Under-Represented Minority"],
    ["USB","Universal Service Bus"],
    ["UTC","Coordinated Universal Time"],
    ["UTF","Unicode Transformation Format"],
    ["UX","User eXperience"],
    ["VAT","Value Added Tax"],
    ["VBO","Value-Based Outcome"],
    ["VCS","Version Control System"],
    ["VDP","Vulnerability Disclosure Program"],
    ["VIP","Virtual IP"],
    ["VLAN","Virtual Local Area Network"],
    ["VM","Virtual Machine"],
    ["VMM","Virtual Machine Manager"],
    ["VNC","Virtual Network Computing"],
    ["VoIP","Voice over Internet Protocol"],
    ["VRRP","Virtual Router Redundancy Protocol"],
    ["VRM","Vendor Risk Management"],
    ["VPA","Vertical Pod Autoscaler"],
    ["VPC","Virtual Private Cloud"],
    ["VPN","Virtual Private Network"],
    ["VSM","Value Stream Mapping"],
    ["vTPM","Virtual Trusted Platform Module"],
    ["VUCA","Volatile + Uncertain + Complex + Ambiguous"],
    ["W3C","World Wide Web Consortium"],
    ["WAAP","Web application and API protection"],
    ["WABD","Well Architected By Design"],
    ["WAF","Web Application Firewall"],
    ["WAF","Well Architected Framework"],
    ["WBS","Work Breakdown Structure"],
    ["WEP","Wired Equivalent Privacy"],
    ["WFH","Work From Home"],
    ["WIP","Work In Process"],
    ["WPA","Wi-Fi Protected Access"],
    ["WSDL","Web Services Description Language"],
    ["WVD","Windows Virtual Desktop"],
    ["X.509","none"],
    ["XaaS","Anything as a Service"],
    ["XKX","External Key Store"],
    ["XDR","Extended Detection and Response"],
    ["XML","Extensible Markup Language"],
    ["XMPP","Extensible Message and Presence Protocol"],
    ["YAML","YAML Ain’t Markup Language"],
    ["YTD","Year-To-Date"],
    ["ZT","Zero Trust"],
    ["ZTA","Zero Trust Architecture"],
    ["ZTS","Zero Trust Security"],
    ["ZTNA","Zero Trust Network Access/Architecture"]
    
  ];
   
  //~~~~~~~~~~~~~~~~~~~~~~~~ FIND ABBVR FOR FULL EXTRACTED TEXT ~~~~~~~~~~~~~~~~~~~~~~~~

  function abbreviation(extractedText) {
    const paragraphs = extractedText.split("\n");
  console.log("extracted text",paragraphs);
    // Highlight words from the dictionary
    let highlightedText = "";
    for (const paragraph of paragraphs) {
      let temp = paragraph + "end_of_line_00000";
      for (let iter = 0; iter < highlightWords.length; iter++) {
        if (
          temp.includes(" " + highlightWords[iter][0] + " ") ||
          temp.includes("(" + highlightWords[iter][0] + ")") ||
          temp.includes(highlightWords[iter][0] + ",") ||
          temp.includes(highlightWords[iter][0] + ".") ||
          temp.includes(highlightWords[iter][0] + "end_of_line_00000")
        ) {
          if (
            temp.includes("(" + highlightWords[iter][1] + ")") ||
            temp.includes(" " + highlightWords[iter][1] + " ") ||
            temp.includes(highlightWords[iter][1] + ".") ||
            temp.includes(highlightWords[iter][1] + ",") ||
            temp.includes(highlightWords[iter][1] + "end_of_line_00000")
          ) {
            continue;
          } else {
            // temp = temp.replace(
            //   "(" + highlightWords[iter][0] + ")",
            //   `<span style="background-color: yellow;">${
            //     "(" + highlightWords[iter][0] + ")"
            //   }</span> `
            // );
            // temp = temp.replace(
            //   " " + highlightWords[iter][0] + " ",
            //   `<span style="background-color: yellow;">${
            //     " " + highlightWords[iter][0] + " "
            //   }</span> `
            // );
          }
        }
      }
      highlightedText =
        highlightedText + temp.replace("end_of_line_00000", "") + "\n\n";
    }
  
// console.log("Added highlight", highlightedText);

    return highlightedText;
  }

  module.exports = { abbreviation };